# Site
title: Shesh
author: Sheshbabu Chinnakonda

# URL
url: http://www.sheshbabu.com/
root: /
permalink: :id/:title/

language: default

# Extensions
theme: light

# Deployment
deploy:
  type: github
  repo: git@github.com:sheshbabu/sheshbabu.github.io.git
  branch: master
