# Site
title: Shesh
author: Sheshbabu Chinnakonda

# URL
url: http://www.sheshbabu.com/
root: /
permalink: posts/:title/

highlight:
  line_number: false
  tab_replace: '    '

language: default

# Extensions
theme: lightspeed

sitemap:
  path: sitemap.xml

# Feed
# Using https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  limit: false

# Deployment
deploy:
  type: git
  repo: https://github.com/sheshbabu/sheshbabu.github.io
  branch: master
